[package]
name = "brainfuck-int"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"
license = "MIT"
authors = ["de_grote"]
readme = "reamde.md"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
